openapi: string
hotel_id: string
master_id: 0
hotel:
  amenity_groups_v2:
    - amenities:
        - id: 0
          name: string
          is_free_v2: 1
      css_class: string
      group_name: string
  check_in_time: string
  check_out_time: string
  front_desk_time_end: string
  front_desk_time_start: string
  description_struct:
    - title: string
      paragraphs:
        - string
      desc_type: string
  policy_struct:
    - title: string
      paragraphs:
        - string
      desc_type: string
      policy_slug: string
  email: string
  images_v2:
    - amenity: 0
      url: string
  is_favorite: true
  kind: string
  phone: string
  region_id: 0
  reviews: 0
  address: string
  city: string
  country: string
  distance: 0
  otahotel_id: string
  master_id: 0
  name: string
  star_rating: 0
  static_currency_code: string
  facts:
    year_built: 0
    year_renovated: 0
    rooms_number: 0
    floors_number: 0
    has_room_wifi: true
    has_hotel_wifi: true
    sockets:
      - socket_type: string
        voltage: 0
        frequency: 0
expired:
  - string
